# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02a273832518a12964cc42eaed1998a067c7897279df949d50e66c861febca55a864e7db200d28c065675d4d4ff0ee69b868cd7ead3606d1c62363509a67b8e5

test:
  secret_key_base: 76ef705a215f1dc40aca0ea242e4ba31b41790520943fbcf9b4255f9e35d540a631dbb9d8641e8a18191505d9c389bcd9581c50271c6ea47d9cae7006c150503

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
